#!/bin/sh

./build clean all --cc=clang || exit $?;

ldd target/lib/libfam.so  | grep "statically linked" || { echo "not statically linked!"; exit 1; }
UNDEFINED_COUNT=$(nm target/lib/libfam.so | grep " U " | wc -l)
if [ "$UNDEFINED_COUNT" -ne 0 ]; then
        echo "Error: Found $UNDEFINED_COUNT undefined symbols"
        nm target/lib/libfam.so | grep " U "
        exit 1
fi

