#!/bin/bash

./build clean all --cc=clang
sudo ./build install

head -c 5G /dev/urandom > ./5gb.txt
ls -l ./5gb.txt
INITIAL_CHECKSUM=`md5sum ./5gb.txt`
echo "initial checksum=${INITIAL_CHECKSUM}"
czip ./5gb.txt
if [ -e ./5gb.txt ]; then
	echo "file was not deleted, exiting!";
	exit 1;
fi
ls -l ./5gb.txt.cz
czip -d ./5gb.txt.cz
ls -l ./5gb.txt
FINAL_CHECKSUM=`md5sum ./5gb.txt`
echo "final checksum=${FINAL_CHECKSUM}"
if [ "${FINAL_CHECKSUM}" != "${INITIAL_CHECKSUM}" ]; then
	echo "checksum mismatch, exiting!";
	exit 1;
fi
rm ./5gb.txt
echo "Success!"
