#!/bin/bash

./build clean all --cc=clang
sudo ./build install

head -c 1G /dev/urandom > ./1gb.txt
INITIAL_CHECKSUM=`md5sum ./1gb.txt`
echo "initial checksum=${INITIAL_CHECKSUM}"
czip ./1gb.txt
if [ -e ./1gb.txt ]; then
	echo "file was not deleted, exiting!";
	exit 1;
fi
ls -l ./1gb.txt.cz
czip -d ./1gb.txt.cz
FINAL_CHECKSUM=`md5sum ./1gb.txt`
echo "final checksum=${FINAL_CHECKSUM}"
if [ "${FINAL_CHECKSUM}" != "${INITIAL_CHECKSUM}" ]; then
	echo "checksum mismatch, exiting!";
	exit 1;
fi
rm ./1gb.txt
echo "Success!"
