#!/bin/sh

if [ "$CI" = "true" ]; then
    sudo apt-get update
    sudo apt-get install -y valgrind
fi

./build clean test --cc=gcc || exit 1; # load bible
./build clean test --cc=gcc --valgrind || exit 1;

