#!/bin/sh

if [ "$CI" = "true" ]; then
    sudo apt-get update
    sudo apt-get install -y valgrind
fi

./build clean test || exit 1; # load bible
./build clean test --cc=clang --valgrind --cflags=-O0 || exit 1;

